// MeDirect account statement (PDF, "rekeningafschrift"): text pieces with
// positions -> the same normalized rows as the CSV reader (core/csv/adapter.js),
// OLDEST FIRST, so duplicates, balance chain and merging are shared.
//
// Layout (generated by MeDirect, one row per movement, newest first):
//   header (page 1): REKENINGNUMMER / NAAM VAN REKENING / IBAN-NUMMER / TYPE REKENING / VALUTA
//                    + box Beginsaldo / Uitgaand / Inkomend / Eindsaldo
//   header (other pages): REKENINGNUMMER / NAAM VAN REKENING / TYPE REKENING
//   table: Datum | Valuta Datum | Omschrijving | Bedrag | Saldo
//     first line: dates, type of movement, "+10,00", "EUR 10,00"
//     detail lines under Omschrijving: "Mededeling: ...", "Van: ..." / "Naar: ...",
//     an IBAN, "Referentie: ...", card payments: "Wisselkoers: ...", "Marge: ...",
//     "Kaart: 1234******5678"; a foreign amount ("USD 6,05") under the amount.
import { parseAmount, NotationError } from '../csv/notation.js';
import { detectStructured } from '../csv/structured.js';
import { normalizeIban } from '../coda/parser.js';
import { detectDirection } from '../csv/adapter.js';
import { add, sum } from '../money.js';
import { lines } from './pdf.js';

const DATE = /^(\d{2})-(\d{2})-(\d{4})$/;
const AMOUNT = /^[+\-−]?\d{1,3}(\.\d{3})*,\d{2}$/;
const CUR_AMOUNT = /^([A-Z]{3})\s+([+\-−]?\d{1,3}(\.\d{3})*,\d{2})$/;
const IBAN = /^[A-Z]{2}\d{2}[A-Z0-9]{8,30}$/;
const MONTHS = { jan: 1, feb: 2, mrt: 3, maa: 3, mar: 3, apr: 4, mei: 5, may: 5, jun: 6, jul: 7, aug: 8, sep: 9, okt: 10, oct: 10, nov: 11, dec: 12 };
const NUM = { decimal: ',', thousands: '.' };

const iso = (text) => {
  const m = DATE.exec(text);
  return m ? `${m[3]}-${m[2]}-${m[1]}` : null;
};
const pageText = (page) => page.items.map((i) => i.text).join(' ');

/** Is this a MeDirect statement? (first page: bank name + the table header) */
export function isMedirectStatement(pdf) {
  const p = pdf.pages[0];
  if (!p || !/medirect/i.test(pageText(p))) return false;
  return Boolean(tableHeader(p));
}

function tableHeader(page) {
  for (const l of lines(page)) {
    const t = l.items.map((i) => i.text.trim());
    if (t.includes('Datum') && t.includes('Valuta Datum') && t.includes('Omschrijving') && t.includes('Bedrag') && t.includes('Saldo')) {
      const x = (name) => l.items.find((i) => i.text.trim() === name).x;
      return { y: l.y, valutaX: x('Valuta Datum'), bedragX: x('Bedrag'), saldoX: x('Saldo') };
    }
  }
  return null;
}

/** Value to the right of a label on (about) the same height. */
function labelValue(page, label, { minDx = 30, maxX = 360 } = {}) {
  const l = page.items.find((i) => i.text.trim().toUpperCase() === label.toUpperCase());
  if (!l) return null;
  const v = page.items.filter((i) => i !== l && i.x > l.x + minDx && i.x < maxX && Math.abs(i.y - l.y) < 4).sort((a, b) => a.x - b.x)[0];
  return v ? v.text.trim() : null;
}

/**
 * @returns {{ encoding, issues, meta, account, snapshot, rows, header, detectedOrder, statement }}
 */
export function parseMedirectStatement(pdf) {
  const issues = [];
  const err = (message, line) => issues.push({ level: 'error', message, line });
  const warn = (message, line) => issues.push({ level: 'warning', message, line });
  const result = { encoding: 'pdf', issues, meta: {}, account: null, snapshot: null, rows: [], header: [], statement: null };
  const first = pdf.pages[0];

  // account
  const iban = normalizeIban(labelValue(first, 'IBAN-NUMMER') ?? labelValue(first, 'REKENINGNUMMER') ?? '');
  if (!iban) {
    err('Het rekeningnummer van de MeDirect-rekening werd niet gevonden op de eerste pagina.');
    return result;
  }
  const type = labelValue(first, 'TYPE REKENING') ?? '';
  const currency = labelValue(first, 'VALUTA');
  if (currency && currency.toUpperCase() !== 'EUR') {
    err(`Rekening in ${currency}: enkel rekeningen in euro worden ondersteund.`);
    return result;
  }
  const kindLabel = type ? type.toLowerCase() : 'rekening';
  result.account = { number: iban, holderName: labelValue(first, 'NAAM VAN REKENING'), accountLabel: `MeDirect ${kindLabel}` };
  pdf.pages.forEach((p) => {
    const n = normalizeIban(labelValue(p, 'REKENINGNUMMER') ?? '');
    if (n && n !== iban) err(`Pagina ${p.number} hoort bij een andere rekening (${n}). Gebruik één afschrift per rekening.`);
  });

  // totals box (page 1)
  const total = (label) => {
    const v = labelValue(first, label, { minDx: 40, maxX: 600 });
    if (v === null) return null;
    try {
      return parseAmount(v, NUM);
    } catch {
      err(`${label} "${v}" is geen geldig bedrag.`);
      return null;
    }
  };
  const statement = { begin: total('Beginsaldo'), out: total('Uitgaand'), in: total('Inkomend'), end: total('Eindsaldo') };
  const period = /(\d{2}-\d{2}-\d{4})\s+tot\s+(\d{2}-\d{2}-\d{4})/.exec(pageText(first));
  if (period) statement.period = { from: iso(period[1]), to: iso(period[2]) };
  result.statement = statement;

  // table rows
  const raw = []; // { page, lines: [{ y, items }] }
  for (const page of pdf.pages) {
    const head = tableHeader(page);
    if (!head) {
      if (page.number === 1) err('De tabel met bewegingen (Datum, Valuta Datum, Omschrijving, Bedrag, Saldo) werd niet gevonden.');
      continue;
    }
    const footer = page.items.find((i) => /^Indien u niet akkoord/i.test(i.text.trim()));
    const endY = footer ? footer.y - 1 : page.height - 75;
    for (const l of lines(page)) {
      if (l.y <= head.y + 1 || l.y >= endY) continue;
      const startsRow = DATE.test(l.items[0].text.trim()) && l.items[0].x < head.valutaX;
      if (startsRow) raw.push({ page: page.number, head, lines: [l] });
      else if (raw.length) raw[raw.length - 1].lines.push(l); // also continues a row from the previous page
      else warn(`Pagina ${page.number}: tekst boven de eerste beweging genegeerd ("${l.items.map((i) => i.text).join(' ')}").`);
    }
  }

  const rows = [];
  raw.forEach((r, index) => {
    const where = `pagina ${r.page}, beweging ${index + 1}`;
    try {
      rows.push({ ...parseRow(r), line: where, filePosition: index });
    } catch (e) {
      if (e instanceof NotationError) err(`${where}: ${e.message}`);
      else throw e;
    }
  });
  if (!rows.length && !issues.some((i) => i.level === 'error')) err('Geen bewegingen gevonden in het afschrift.');
  if (issues.some((i) => i.level === 'error')) return result;

  // order: newest first in the file (derived from the balance chain)
  const dir = detectDirection(rows);
  if (!dir) {
    err('De saldoketen van het afschrift sluit niet: een beweging werd niet correct gelezen.');
    return result;
  }
  result.detectedOrder = dir === 'oldest-first' ? 'oldest-first' : 'newest-first';
  const ordered = result.detectedOrder === 'newest-first' ? [...rows].reverse() : rows;

  // statement checks: begin + in - out = end, and the movements match the totals
  const fmt = (m) => (m / 1000).toFixed(2).replace('.', ',');
  if (statement.begin !== null && statement.end !== null && statement.in !== null && statement.out !== null) {
    if (add(add(statement.begin, statement.in), -statement.out) !== statement.end) err(`Saldocontrole afschrift: beginsaldo ${fmt(statement.begin)} + inkomend ${fmt(statement.in)} − uitgaand ${fmt(statement.out)} is niet het eindsaldo ${fmt(statement.end)}.`);
    const inSum = sum(ordered.filter((x) => x.amount > 0).map((x) => x.amount));
    const outSum = -sum(ordered.filter((x) => x.amount < 0).map((x) => x.amount));
    if (inSum !== statement.in || outSum !== statement.out) err(`Saldocontrole afschrift: de bewegingen (inkomend ${fmt(inSum)}, uitgaand ${fmt(outSum)}) komen niet overeen met de totalen van het afschrift (inkomend ${fmt(statement.in)}, uitgaand ${fmt(statement.out)}). Mogelijk werd een beweging niet gelezen.`);
    const oldest = ordered[0];
    if (add(statement.begin, oldest.amount) !== oldest.balanceAfter) err(`Saldocontrole afschrift: beginsaldo ${fmt(statement.begin)} + eerste beweging ${fmt(oldest.amount)} is niet het saldo ${fmt(oldest.balanceAfter)} na die beweging.`);
    if (ordered[ordered.length - 1].balanceAfter !== statement.end) err(`Saldocontrole afschrift: het saldo na de laatste beweging is niet het eindsaldo ${fmt(statement.end)}.`);
  } else {
    warn('De totalen van het afschrift (beginsaldo, uitgaand, inkomend, eindsaldo) werden niet gevonden; enkel de saldoketen werd gecontroleerd.');
  }
  result.rows = ordered;
  return result;
}

function parseRow({ lines: ls, head }) {
  const firstLine = ls[0].items.map((i) => ({ ...i, text: i.text.trim() }));
  const entryDate = iso(firstLine[0].text);
  const valueItem = firstLine.find((i, k) => k > 0 && DATE.test(i.text) && i.x < head.valutaX + 40);
  const right = (i) => i.x > head.bedragX - 60;
  const amountItem = firstLine.find((i) => right(i) && AMOUNT.test(i.text) && i.x < head.saldoX - 15);
  const saldoItem = firstLine.find((i) => right(i) && CUR_AMOUNT.test(i.text));
  if (!amountItem) throw new NotationError('bedrag niet gevonden');
  if (!saldoItem) throw new NotationError('saldo niet gevonden');
  const saldo = CUR_AMOUNT.exec(saldoItem.text);
  if (saldo[1] !== 'EUR') throw new NotationError(`saldo in ${saldo[1]} wordt niet ondersteund`);
  const descFirst = firstLine.filter((i) => i !== firstLine[0] && i !== valueItem && i !== amountItem && i !== saldoItem);
  const descX = descFirst.length ? descFirst[0].x : head.valutaX + 70;
  const bankType = descFirst.map((i) => i.text).join(' ').trim() || null;

  // detail lines and the foreign amount
  const details = [];
  let foreign = null;
  for (const l of ls.slice(1)) {
    for (const i of l.items) {
      const t = i.text.trim();
      if (!t) continue;
      if (right(i) && CUR_AMOUNT.test(t)) foreign = CUR_AMOUNT.exec(t);
      else details.push(t);
    }
  }
  const fields = {};
  const extra = [];
  let last = null;
  for (const d of details) {
    const m = /^(Mededeling|Van|Naar|Referentie|Wisselkoers|Marge|Kaart):\s*(.*)$/i.exec(d);
    const compact = d.replace(/\s/g, '');
    if (m) {
      last = m[1].toLowerCase();
      fields[last] = m[2].trim();
    } else if (IBAN.test(compact) && !fields.iban) {
      fields.iban = compact;
      last = null;
    } else if (last === 'mededeling' || last === 'van' || last === 'naar') {
      fields[last] += ` ${d}`; // wrapped text
    } else extra.push(d);
  }
  const amount = parseAmount(amountItem.text.replace('−', '-'), NUM);
  const balanceAfter = parseAmount(saldo[2].replace('−', '-'), NUM);
  let name = fields.van ?? fields.naar ?? '';
  const isCard = /kaart/i.test(bankType ?? '') || fields.kaart !== undefined;
  let card = null;
  if (isCard) {
    const dm = /\s+(\d{1,2})-([a-zé]{3,4})\.?$/i.exec(name);
    let paidAt = null;
    if (dm && MONTHS[dm[2].toLowerCase().slice(0, 3)]) {
      const month = MONTHS[dm[2].toLowerCase().slice(0, 3)];
      let year = Number(entryDate.slice(0, 4));
      const candidate = `${year}-${String(month).padStart(2, '0')}-${String(Number(dm[1])).padStart(2, '0')}`;
      if (candidate > entryDate) year--; // purchase in December, booked in January
      paidAt = `${year}-${String(month).padStart(2, '0')}-${String(Number(dm[1])).padStart(2, '0')}`;
      name = name.slice(0, dm.index).trim();
    }
    card = { merchantLine: fields.van ?? fields.naar ?? null, merchant: name || null, postcode: null, city: null, country: null, paidAt, maskedCard: fields.kaart ?? null };
  }
  const commText = [fields.mededeling, ...extra].filter(Boolean).join('\n');
  const structured = detectStructured(commText);
  let costs = null;
  if (fields.marge !== undefined) {
    let marginAmount = null;
    try {
      marginAmount = parseAmount(fields.marge.replace('€', '').trim(), NUM);
    } catch {
      /* kept as text */
    }
    costs = { text: `Marge: ${fields.marge}`, amount: marginAmount };
  }
  const exchangeRate = foreign || fields.wisselkoers ? [foreign ? `${foreign[1]} ${foreign[2]}` : null, fields.wisselkoers ? `koers ${fields.wisselkoers}` : null].filter(Boolean).join(' · ') : null;
  const cp = fields.iban ? normalizeIban(fields.iban) : '';
  return {
    bankRef: fields.referentie ?? null,
    entryDate,
    valueDate: valueItem ? iso(valueItem.text) : null,
    statementYear: null,
    statementNumber: null,
    bankType,
    amount,
    balanceAfter,
    counterparty: { account: cp, isIban: Boolean(cp), bic: '', name, street: null, postcode: null, city: null, country: null },
    communication: { structured: structured?.structured ?? null, structuredValid: structured?.structuredValid ?? null, text: commText },
    card,
    costs,
    exchangeRate,
    ownAccount: null,
  };
}
