// Minimal PDF text reader: enough for bank statements generated by software
// (no scans). Returns the text pieces per page with their position.
//   - objects are found by scanning "n g obj" (also works without a valid xref)
//   - streams: no filter or /FlateDecode
//   - fonts: Type0/Identity-H with /ToUnicode, simple fonts with /ToUnicode or WinAnsi
//   - text operators: BT ET Tf Td TD Tm T* TL Tj TJ ' " and q Q cm for the position
// Not supported (clear error): encryption, object streams for pages, other filters.
import { inflate } from './inflate.js';
import { CP1252_HIGH } from '../coda/decode.js';

export class PdfError extends Error {}

class Ref {
  constructor(num, gen) {
    this.num = num;
    this.gen = gen;
  }
}
class Name {
  constructor(name) {
    this.name = name;
  }
}
const isWs = (c) => c === 32 || c === 10 || c === 13 || c === 9 || c === 12 || c === 0;
const isDelim = (c) => c === 40 || c === 41 || c === 60 || c === 62 || c === 91 || c === 93 || c === 123 || c === 125 || c === 47 || c === 37;

/** Tokenizer/parser on a byte array, used for objects and content streams. */
class Lexer {
  constructor(bytes, pos = 0) {
    this.b = bytes;
    this.pos = pos;
  }
  skipWs() {
    const b = this.b;
    for (;;) {
      while (this.pos < b.length && isWs(b[this.pos])) this.pos++;
      if (b[this.pos] === 37) {
        while (this.pos < b.length && b[this.pos] !== 10 && b[this.pos] !== 13) this.pos++; // comment
      } else return;
    }
  }
  /** Next token: { t: 'num'|'name'|'str'|'hex'|'op'|'['|']'|'<<'|'>>'|'eof', v } */
  token() {
    this.skipWs();
    const b = this.b;
    if (this.pos >= b.length) return { t: 'eof' };
    const c = b[this.pos];
    if (c === 91 || c === 93) {
      this.pos++;
      return { t: c === 91 ? '[' : ']' };
    }
    if (c === 60 && b[this.pos + 1] === 60) {
      this.pos += 2;
      return { t: '<<' };
    }
    if (c === 62 && b[this.pos + 1] === 62) {
      this.pos += 2;
      return { t: '>>' };
    }
    if (c === 60) {
      const end = b.indexOf(62, this.pos);
      if (end < 0) throw new PdfError('Onvolledige hexadecimale tekst.');
      let hex = '';
      for (let i = this.pos + 1; i < end; i++) if (!isWs(b[i])) hex += String.fromCharCode(b[i]);
      this.pos = end + 1;
      if (hex.length % 2) hex += '0';
      const out = new Uint8Array(hex.length / 2);
      for (let i = 0; i < out.length; i++) out[i] = parseInt(hex.substr(i * 2, 2), 16);
      return { t: 'str', v: out };
    }
    if (c === 40) return { t: 'str', v: this.literal() };
    if (c === 47) {
      let s = '';
      this.pos++;
      while (this.pos < b.length && !isWs(b[this.pos]) && !isDelim(b[this.pos])) {
        if (b[this.pos] === 35) {
          s += String.fromCharCode(parseInt(String.fromCharCode(b[this.pos + 1], b[this.pos + 2]), 16));
          this.pos += 3;
        } else s += String.fromCharCode(b[this.pos++]);
      }
      return { t: 'name', v: s };
    }
    let s = '';
    while (this.pos < b.length && !isWs(b[this.pos]) && !isDelim(b[this.pos])) s += String.fromCharCode(b[this.pos++]);
    if (s === '') {
      this.pos++; // stray delimiter
      return this.token();
    }
    if (/^[+-]?(\d+\.?\d*|\.\d+)$/.test(s)) return { t: 'num', v: Number(s) };
    return { t: 'op', v: s };
  }
  literal() {
    const b = this.b;
    const out = [];
    let depth = 1;
    this.pos++;
    while (this.pos < b.length) {
      const c = b[this.pos++];
      if (c === 92) {
        const e = b[this.pos++];
        const map = { 110: 10, 114: 13, 116: 9, 98: 8, 102: 12 };
        if (map[e] !== undefined) out.push(map[e]);
        else if (e >= 48 && e <= 55) {
          let oct = e - 48;
          for (let k = 0; k < 2 && b[this.pos] >= 48 && b[this.pos] <= 55; k++) oct = oct * 8 + (b[this.pos++] - 48);
          out.push(oct & 255);
        } else if (e === 13) {
          if (b[this.pos] === 10) this.pos++;
        } else if (e !== 10) out.push(e);
      } else if (c === 40) {
        depth++;
        out.push(c);
      } else if (c === 41) {
        if (--depth === 0) break;
        out.push(c);
      } else out.push(c);
    }
    return Uint8Array.from(out);
  }
  /** A complete object (dict, array, ref, number, ...). */
  object(tok = this.token()) {
    if (tok.t === '<<') {
      const d = {};
      for (;;) {
        const k = this.token();
        if (k.t === '>>' || k.t === 'eof') return d;
        if (k.t !== 'name') throw new PdfError('Ongeldige woordenlijst in de PDF.');
        d[k.v] = this.object();
      }
    }
    if (tok.t === '[') {
      const a = [];
      for (;;) {
        const t = this.token();
        if (t.t === ']' || t.t === 'eof') return a;
        a.push(this.object(t));
      }
    }
    if (tok.t === 'num') {
      // "n g R" reference?
      const save = this.pos;
      const t2 = this.token();
      if (t2.t === 'num' && Number.isInteger(tok.v) && Number.isInteger(t2.v)) {
        const t3 = this.token();
        if (t3.t === 'op' && t3.v === 'R') return new Ref(tok.v, t2.v);
      }
      this.pos = save;
      return tok.v;
    }
    if (tok.t === 'name') return new Name(tok.v);
    if (tok.t === 'str') return tok.v;
    if (tok.t === 'op') return tok.v === 'true' ? true : tok.v === 'false' ? false : tok.v === 'null' ? null : tok.v;
    return null;
  }
}

/** Parse the PDF structure: objects by number. */
function readObjects(bytes) {
  const text = latin1(bytes);
  const objects = new Map();
  const re = /(\d+)\s+(\d+)\s+obj\b/g;
  let m;
  while ((m = re.exec(text))) {
    const lx = new Lexer(bytes, m.index + m[0].length);
    let value;
    try {
      value = lx.object();
    } catch {
      continue;
    }
    lx.skipWs();
    let stream = null;
    if (text.startsWith('stream', lx.pos)) {
      let start = lx.pos + 6;
      if (bytes[start] === 13) start++;
      if (bytes[start] === 10) start++;
      stream = { start };
    }
    objects.set(Number(m[1]), { value, stream });
    if (stream) {
      // jump over the stream data (it may contain "obj" by accident)
      const end = text.indexOf('endstream', stream.start);
      if (end > 0) re.lastIndex = end;
    }
  }
  return { objects, text };
}

function latin1(bytes) {
  let s = '';
  for (let i = 0; i < bytes.length; i += 8192) s += String.fromCharCode.apply(null, bytes.subarray(i, i + 8192));
  return s;
}

/** @param opts { maxPages }: read only the first pages (e.g. for detection) */
export function parsePdf(bytes, { maxPages = Infinity } = {}) {
  if (latin1(bytes.subarray(0, 1024)).indexOf('%PDF-') < 0) throw new PdfError('Geen PDF-bestand.');
  const { objects, text } = readObjects(bytes);
  if (/\/Encrypt\s/.test(text.slice(-4096))) throw new PdfError('De PDF is versleuteld en kan niet gelezen worden.');
  const get = (v) => {
    for (let i = 0; i < 32 && v instanceof Ref; i++) v = objects.get(v.num)?.value ?? null;
    return v;
  };
  const nameOf = (v) => (get(v) instanceof Name ? get(v).name : null);
  const streamData = (ref) => {
    const o = ref instanceof Ref ? objects.get(ref.num) : null;
    if (!o?.stream) throw new PdfError('Verwachte stroom ontbreekt in de PDF.');
    const dict = o.value;
    let len = get(dict.Length);
    let raw;
    if (Number.isInteger(len) && o.stream.start + len <= bytes.length) raw = bytes.subarray(o.stream.start, o.stream.start + len);
    else {
      const end = text.indexOf('endstream', o.stream.start);
      raw = bytes.subarray(o.stream.start, end);
    }
    const filters = [get(dict.Filter)].flat().filter(Boolean).map((f) => (f instanceof Name ? f.name : nameOf(f)));
    for (const f of filters) {
      if (f === 'FlateDecode' || f === 'Fl') {
        if (get(dict.DecodeParms)) throw new PdfError('PDF-stroom met voorspeller wordt niet ondersteund.');
        raw = inflate(raw);
      } else throw new PdfError(`PDF-filter ${f} wordt niet ondersteund.`);
    }
    return raw;
  };

  // page tree
  const catalog = [...objects.values()].map((o) => o.value).find((v) => v && typeof v === 'object' && nameOf(v.Type) === 'Catalog');
  if (!catalog) throw new PdfError('PDF-structuur niet herkend (geen catalogus).');
  const pageDicts = [];
  const walk = (node, inherited, depth) => {
    node = get(node);
    if (!node || depth > 50) return;
    const inh = { Resources: node.Resources ?? inherited.Resources, MediaBox: node.MediaBox ?? inherited.MediaBox };
    if (nameOf(node.Type) === 'Pages' || node.Kids) for (const k of get(node.Kids) ?? []) walk(k, inh, depth + 1);
    else pageDicts.push({ node, ...inh });
  };
  walk(catalog.Pages, {}, 0);
  if (!pageDicts.length) throw new PdfError('De PDF bevat geen pagina’s.');

  const fontCache = new Map();
  const fontFor = (ref) => {
    const key = ref instanceof Ref ? ref.num : ref;
    if (fontCache.has(key)) return fontCache.get(key);
    const f = get(ref) ?? {};
    const twoByte = nameOf(f.Subtype) === 'Type0';
    let map = null;
    if (f.ToUnicode instanceof Ref) map = parseCMap(latin1(streamData(f.ToUnicode)));
    const font = { twoByte, map };
    fontCache.set(key, font);
    return font;
  };

  const pages = pageDicts.slice(0, maxPages).map((p, index) => {
    const box = (get(p.MediaBox) ?? [0, 0, 595.28, 841.89]).map(get);
    const height = box[3] - box[1];
    const res = get(p.Resources) ?? {};
    const fonts = get(res.Font) ?? {};
    const contents = [get(p.node.Contents) instanceof Array ? get(p.node.Contents) : [p.node.Contents]].flat().filter(Boolean);
    const parts = contents.map((c) => streamData(c));
    const all = new Uint8Array(parts.reduce((n, x) => n + x.length + 1, 0));
    let off = 0;
    for (const x of parts) {
      all.set(x, off);
      off += x.length;
      all[off++] = 10;
    }
    const items = runContent(all, (name) => (fonts[name] ? fontFor(fonts[name]) : { twoByte: false, map: null })).map((it) => ({ ...it, x: it.x - box[0], y: height - (it.y - box[1]) }));
    items.sort((a, b) => a.y - b.y || a.x - b.x);
    return { number: index + 1, width: box[2] - box[0], height, items };
  });
  return { pages };
}

/** ToUnicode CMap: code (number) -> string */
export function parseCMap(src) {
  const map = new Map();
  const hexToStr = (h) => {
    let s = '';
    for (let i = 0; i + 4 <= h.length; i += 4) s += String.fromCharCode(parseInt(h.substr(i, 4), 16));
    if (h.length === 2) s = String.fromCharCode(parseInt(h, 16));
    return s;
  };
  for (const block of src.matchAll(/beginbfchar([\s\S]*?)endbfchar/g)) {
    for (const m of block[1].matchAll(/<([0-9a-fA-F]+)>\s*<([0-9a-fA-F]*)>/g)) map.set(parseInt(m[1], 16), hexToStr(m[2]));
  }
  for (const block of src.matchAll(/beginbfrange([\s\S]*?)endbfrange/g)) {
    for (const m of block[1].matchAll(/<([0-9a-fA-F]+)>\s*<([0-9a-fA-F]+)>\s*(<([0-9a-fA-F]+)>|\[([^\]]*)\])/g)) {
      const a = parseInt(m[1], 16);
      const b = parseInt(m[2], 16);
      if (b - a > 65535) continue;
      if (m[4] !== undefined) {
        const base = parseInt(m[4].slice(-4), 16);
        const prefix = hexToStr(m[4].slice(0, -4));
        for (let c = a; c <= b; c++) map.set(c, prefix + String.fromCharCode(base + c - a));
      } else {
        const list = [...m[5].matchAll(/<([0-9a-fA-F]*)>/g)].map((x) => hexToStr(x[1]));
        for (let c = a; c <= b && c - a < list.length; c++) map.set(c, list[c - a]);
      }
    }
  }
  return map;
}

const WIN_ANSI = (byte) => String.fromCharCode(byte >= 0x80 && byte <= 0x9f ? CP1252_HIGH[byte - 0x80] : byte);

function decodeString(bytes, font) {
  let s = '';
  if (font.twoByte) {
    for (let i = 0; i + 1 < bytes.length; i += 2) {
      const code = (bytes[i] << 8) | bytes[i + 1];
      s += font.map?.get(code) ?? '�';
    }
  } else {
    for (const byte of bytes) s += font.map?.get(byte) ?? WIN_ANSI(byte);
  }
  return s;
}

const mul = (a, b) => [a[0] * b[0] + a[1] * b[2], a[0] * b[1] + a[1] * b[3], a[2] * b[0] + a[3] * b[2], a[2] * b[1] + a[3] * b[3], a[4] * b[0] + a[5] * b[2] + b[4], a[4] * b[1] + a[5] * b[3] + b[5]];
const ID = [1, 0, 0, 1, 0, 0];

/** Run a content stream; returns [{ x, y (PDF space), text, size }] */
function runContent(bytes, fontByName) {
  const lx = new Lexer(bytes);
  const items = [];
  let ctm = ID;
  const stack = [];
  let tm = ID;
  let tlm = ID;
  let leading = 0;
  let font = { twoByte: false, map: null };
  let size = 0;
  let ops = [];
  const show = (str) => {
    const text = decodeString(str, font);
    if (!text) return;
    const m = mul(tm, ctm);
    items.push({ x: m[4], y: m[5], text, size: size * Math.hypot(m[0], m[1]) });
  };
  const nextLine = (tx, ty) => {
    tlm = mul([1, 0, 0, 1, tx, ty], tlm);
    tm = tlm;
  };
  for (;;) {
    const t = lx.token();
    if (t.t === 'eof') break;
    if (t.t !== 'op') {
      ops.push(lx.object(t));
      continue;
    }
    const a = ops;
    ops = [];
    switch (t.v) {
      case 'q':
        stack.push(ctm);
        break;
      case 'Q':
        ctm = stack.pop() ?? ID;
        break;
      case 'cm':
        if (a.length >= 6) ctm = mul(a.slice(-6), ctm);
        break;
      case 'BT':
        tm = ID;
        tlm = ID;
        break;
      case 'Tf':
        font = fontByName(a[0] instanceof Name ? a[0].name : '');
        size = a[1] ?? 0;
        break;
      case 'TL':
        leading = a[0] ?? 0;
        break;
      case 'Td':
        nextLine(a[0] ?? 0, a[1] ?? 0);
        break;
      case 'TD':
        leading = -(a[1] ?? 0);
        nextLine(a[0] ?? 0, a[1] ?? 0);
        break;
      case 'Tm':
        if (a.length >= 6) tlm = tm = a.slice(-6);
        break;
      case 'T*':
        nextLine(0, -leading);
        break;
      case 'Tj':
        if (a[0] instanceof Uint8Array) show(a[0]);
        break;
      case "'":
        nextLine(0, -leading);
        if (a[0] instanceof Uint8Array) show(a[0]);
        break;
      case '"':
        nextLine(0, -leading);
        if (a[2] instanceof Uint8Array) show(a[2]);
        break;
      case 'TJ': {
        const parts = (a[0] ?? []).filter((x) => x instanceof Uint8Array);
        const joined = new Uint8Array(parts.reduce((n, x) => n + x.length, 0));
        let o = 0;
        for (const x of parts) {
          joined.set(x, o);
          o += x.length;
        }
        show(joined);
        break;
      }
      case 'BI': {
        // inline image: skip to EI
        const s = latin1(bytes.subarray(lx.pos));
        const e = s.search(/\sEI(\s|$)/);
        lx.pos += e < 0 ? s.length : e + 3;
        break;
      }
      default:
        break;
    }
  }
  return items;
}

/** Group text pieces into lines: same y (± tolerance), sorted by x. */
export function lines(page, tol = 1.5) {
  const out = [];
  for (const it of page.items) {
    const line = out.find((l) => Math.abs(l.y - it.y) <= tol);
    if (line) line.items.push(it);
    else out.push({ y: it.y, items: [it] });
  }
  for (const l of out) l.items.sort((a, b) => a.x - b.x);
  return out.sort((a, b) => a.y - b.y);
}
